builds:
  - id: linux
    main: .
    binary: NZBreX
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    ldflags:
      - "-s -w -X main.appVersion={{.Version}}"
    env:
      - CGO_ENABLED=0

  - id: windows
    main: .
    binary: NZBreX.exe
    goos:
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    ldflags:
      - "-s -w -X main.appVersion={{.Version}}"
    env:
      - CGO_ENABLED=0

archives:
  - id: linux
    ids: [linux]
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - "{{ .Binary }}"

  - id: windows
    ids: [windows]
    formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - "{{ .Binary }}"
