version: 2

project_name: NZBreX
dist: dist

builds:
  - id: default
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}"
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - docs/**

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: deb
    formats: [deb]
    vendor: NZBreX
    maintainer: "NZBreX <nzbrex@usenet-server.com>"
    description: "NZBreX - a cmd line tool to re-upload articles missing from providers"
    homepage: "https://github.com/go-while/NZBreX"
    license: "MIT"
    bindir: /usr/bin
    file_name_template: NZBreX_{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}.deb

release:
  github:
    owner: go-while
    name: NZBreX
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  use: github
