version: 2

project_name: NZBreX
dist: dist

builds:
  - id: linux
    main: .
    binary: NZBreX
    ignore:
      - goarch: 386
      - goos: windows
      - goos: darwin
      - goos: freebsd
      - goos: openbsd
      - goos: netbsd
    goos:
      - linux
      #- darwin
      #- freebsd
      #- openbsd
      #- netbsd
    goarch:
      - amd64
      #- arm64
      #- 386
      #- arm
    ldflags:
      - "-s -w -X main.appVersion={{.Version}}"
    env:
      - CGO_ENABLED=1

  #- id: windows
  #  main: .
  #  binary: NZBreX
  #  goos:
  #    - windows
  #  goarch:
  #    - amd64
  #    #- arm64
  #    #- 386
  #    #- arm
  #  ldflags:
  #    - "-s -w -X main.appVersion={{.Version}}"
  #  env:
  #    - CGO_ENABLED=0

archives:
  - id: unix
    ids: [linux]
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - "{{ .ArtifactPath }}"

  #- id: win
  #  ids: [windows]
  #  formats: [zip]
  #  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  #  files:
  #    - LICENSE*
  #    - README*
  #    - "{{ .ArtifactPath }}"

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: deb
    formats: [deb]
    vendor: NZBreX
    maintainer: "NZBreX <nzbrex@usenet-server.com>"
    description: "NZBreX - a cmd line tool to re-upload articles missing from providers"
    homepage: "https://github.com/go-while/NZBreX"
    license: "MIT"
    bindir: /usr/bin
    file_name_template: NZBreX_{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}.deb

snapshot:
  version_template: "{{ if .Tag }}{{ .Tag }}{{ else }}{{ .Branch }}-SNAPSHOT-{{ .ShortCommit }}{{ end }}"

release:
  github:
    owner: go-while
    name: NZBreX
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  use: github
