name: GoReleaser Test Build

on:
  push:
    branches:
      - 'gpt-tests-1748440700'
    tags:
      - "test*"
  release:
    types: [published]
  workflow_dispatch:
  repository_dispatch:
  pull_request:
    branches:
      #- main
      - testing


permissions:
  contents: write
  packages: read

jobs:
  goreleaser:
    name: GoReleaser Test
    runs-on: [self-hosted, ubu2204-gor] # or whatever your dedicated runner label is

#    env:
#      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clean build directory
        run: rm -rf dist build

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      # Uncomment if you need platform-specific build dependencies
      # - name: Install build dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y musl-tools zip curl dpkg-dev

#      #  set REF_NAME to "branch-name/sha::7" if not release
#      - name: "Set Ref Name Variable"
#        run: |
#          if [ "$GITHUB_EVENT_NAME" != "release" ]; then
#            ref_name="${GITHUB_REF_NAME:-${GITHUB_REF##*/}}/${GITHUB_SHA::7}"
#          else
#            ref_name="${GITHUB_REF_NAME:-${GITHUB_REF##*/}}"
#          fi
#          echo "REF_NAME=${ref_name}" >> "$GITHUB_ENV"
#        #env:
#        #  GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: "Set Ref Name Variable"
        run: |
          #if [ "$GITHUB_EVENT_NAME" != "release" ]; then
          #  ref_name=${GITHUB_SHA::7}
          #else
          #  ref_name=${{ github.ref_name }}
          #fi
          echo "REF_NAME=${ref_name}" >> "$GITHUB_ENV"
          echo "GITHUB_SHA7=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Run GoReleaser (Test Build)
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --snapshot

      - name: Post-upload artifacts
        run: .goreleaser/post_upload_GaRuS.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          #GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_REF_NAME: ${{ env.REF_NAME }}
          GITHUB_SHA7: ${{ env.GITHUB_SHA7 }}
          BUILD_TEST_UPLOAD_TOKEN: ${{ secrets.BUILD_TEST_UPLOAD_TOKEN }}

      - name: Clean build directory
        run: rm -rf dist build
