name: "Self-Hosted GoReleaser"

on:
  push:
    branches:
      - 'gpt-tests-1748467242'
    tags:
      - "test*"
  release:
    types: [published]
  workflow_dispatch:
  repository_dispatch:
  pull_request:
    branches:
      #- main
      - testing

permissions:
  contents: write
  packages: read

jobs:
  goreleaser:
    name: "GoReleaser Test Build"
    runs-on: [self-hosted, ubu2204-gor]
#    env:
#      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "@Start Clean directory"
        run: |
          echo "deleting workspace"
          rm -rfv dist build ${{ github.workspace }}/
          mkdir -vp ${{ github.workspace }}

      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      # Uncomment if you need platform-specific build dependencies
      # - name: Install build dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y musl-tools zip curl dpkg-dev

      #- name: "Restore go cache"
      #  run: runner/go-cache-restore.sh

      - name: "Run GoReleaser (Test Build)"
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --snapshot

      - name: "Set GaRuS Variables"
        run: echo "GITHUB_SHA7=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: "Upload binary to private GaRuS (Git-actions-Runner-upload-Server)"
        run: .goreleaser/post_upload_GaRuS.sh
        env:
          BUILD_TEST_UPLOAD_TOKEN: ${{ secrets.BUILD_TEST_UPLOAD_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_SHA7: ${{ env.GITHUB_SHA7 }}
          COMPILER: "GOR"

      #- name: "Backup go cache"
      #  run: runner/go-cache-backup.sh

      - name: "@End Clean directory"
        run: |
          echo "deleting workspace"
          rm -rfv dist build ${{ github.workspace }}/
          mkdir -vp ${{ github.workspace }}
