name: GoReleaser Test Build

on:
  push:
    branches:
      # - gpt-tests-** # use ** to match any number of directories or subdirectories.
      - gpt-tests-1748440700
      - tests**
  release:
    types: [published]
  workflow_dispatch:
  repository_dispatch:
  pull_request:
  push:
    tags:
      - "test*"


permissions:
  contents: write
  packages: read

jobs:
  goreleaser:
    name: GoReleaser Test
    runs-on: [self-hosted, ubu2204-gor] # or whatever your dedicated runner label is

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_TEST_UPLOAD_TOKEN: ${{ secrets.BUILD_TEST_UPLOAD_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_REF_NAME: ${{ github.ref_name }}

    steps:
      - name: Clean build directory
        run: rm -rf dist build

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      # Uncomment if you need platform-specific build dependencies
      # - name: Install build dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y musl-tools zip curl dpkg-dev

      - name: Run GoReleaser (Test Build)
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --snapshot

      - name: Post-upload artifacts
        run: .goreleaser/post_upload_GaRuS.sh
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          BUILD_TEST_UPLOAD_TOKEN: ${{ secrets.BUILD_TEST_UPLOAD_TOKEN }}
